#!/bin/sh
[ -f /etc/banner ] && cat /etc/banner

check=`ifconfig|grep -e mesh0|cut -f1 -d" "`
if [ -f /var/sysinfo/model ];
then
  echo "Router model: `cat /var/sysinfo/model`"
  echo ""
elif [ "$check" = "mesh0" ]; then
  echo "Router model: [`iwinfo mesh0 info |grep -e Hardware|cut -f2 -d[`"
  echo""
else
  echo ""
fi


export PATH=/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/bin
export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
export HOME=${HOME:-/root}
export PS1='\u@\h:\w\$ '

[ -x /bin/more ] || alias more=less
[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi

[ -z "$KSH_VERSION" -o \! -s /etc/mkshrc ] || . /etc/mkshrc

[ -x /usr/bin/arp ] || arp() { cat /proc/net/arp; }
[ -x /usr/bin/ldd ] || ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }

alias nodes="echo /routes|nc 127.0.0.1 2006"
alias links="echo /links |nc 127.0.0.1 2006"
alias neig="echo /neighbors|nc 127.0.0.1 2006"
alias help='cat /etc/commands'
alias edit=nano
